### ISSUE TITLE
Possibility to see raw value of a PV

### ISSUE THREAD

**Issue by juliendufey** [yamcs/yamcs-studio#45]
Currently it is not possible to see the raw value of a parameter, only the engineering one. 
For ASIM, some values such as a checksum or a software version are contained in the data field of the command verification responses. 
Currently it would be displayed as UNDEF since there is no engineering value associated with the checksum or software version. The raw value should be available somehow.
Raw values can also help identify mission database or display issues. 

Suggestion to display the raw value: 
- right clicking a PV field, select PV info and the raw value would be displayed there
- raw value displayed when hovering over a PV field

Thanks

**Comment by fqqb** [comment]
v1.0.0 which is under preparation will include a first stab at this ticket:
![screen shot 2018-03-06 at 19 20 49](https://user-images.githubusercontent.com/145170/37050261-b4dbe498-2173-11e8-909b-3686da912b71.png)
The dialog content follows incoming values.

It took a while to get to this issue because we had to refactor other related code first.

Keeping this issue open because would also like to have it be possible to use directly the raw value in a widget for example.

**Comment by juliendufey** [comment]
Hi Fabian,

Thanks for the notification.
Is the feature committed and already available in the latest beta 
version available here?
https://github.com/yamcs/yamcs-studio/releases/tag/v1.0.0-beta.34
Thanks,

Julien

*Julien Dufey *
B.USOC Operations Engineer & Ground Controller
office: + 32 2 416 05 91
B.USOC: + 32 2 373 04 22

**Comment by fqqb** [comment]
It's not, it was developed on a different branch which is already targeting a later version of Yamcs Server (v4) than you are currently using. We're now looking with Tom to see if we can make that release backwards compatible with Yamcs v3. If so, we'll cut a non-beta 1.0.0 release that will include this feature (and others not included in beta.34).

**Comment by tomvanbraeckel** [comment]
I think this is done now, right? Yamcs Studio v1.0.0 and v1.0.1 has been released and it has this feature!

**Comment by fqqb** [comment]
Yes, the main request is. 
I've extracted the follow-on functionality (which is more a personal desire) in #53
