### ISSUE TITLE
Switching between Display Builder and Display Runner usability improvements

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#54]
The shortcut to go to "OPI runner" in Yamcs Studio v1.0.0 is CTRL-G but is there also a shortcut (the same one would do) to go open the "OPI builder"? That would be convenient and also easier to explain while supporting a user.

Also, is there any menu entry in the textual top menu bar to open the runner/builder or switch between these? That would also make it easier to explain how this switching works, where to find the button,...

Currently, to explain to users of Yamcs Studio v1.0.x how to switch between Display Runner and Display Builder, we need to refer to: "the little green "Play" or "Hammer" button in the top icon bar, 4th icon from the left" but it would be easier if we can refer to "Window" - "Open OPI Runner" or something similar.

**Comment by fqqb** [comment]
Next release will bring some improvements here:

* There will always be Display Builder and Display Runner entries in the Window menu. These use shortcuts CTRL-1 and CTRL-2. 
* CTRL-G still works like before, but I'm not sure where to go with that one (keep or no keep), so that will be revisited in the future. Maybe could turn into some generic switch operation, but you can already do that with alt-tab, so not sure yet.

![image](https://user-images.githubusercontent.com/145170/40003497-c1d7fdde-5793-11e8-8bdb-f6e46a9210a2.png)
