### ISSUE TITLE
Yamcs Studio v1.0.2 - issueCommand() function wrongly interpreting quotes

### ISSUE THREAD

**Issue by kstruyven** [yamcs/yamcs-studio#78]
When sending a command with a display, we use the issueCommand() function that has the complete command as argument (string). When that command has an argument whichs value is a string, that string is not allowed to contain a comma since it will interpret it as a new argument and thus returning a ArrayIndexOutofBoundsException. Adding quotes around the argument is also producing the same error.

**Comment by fqqb** [comment]
I have committed a change such that you can now also issue a command by passing arguments in a dictionary. For example:

`Yamcs.issueCommand('/some/command', { arg1: "a , comma", arg2: 1234})`

I'm thinking of deprecating the original issueCommand in favour of this new one (but it will remains functional for now).

Will you need a new v1.0.x release? v1.0.2 is very old btw.

**Comment by fqqb** [comment]
The change is included as of yamcs-studio v1.0.6.

I would recommend to use this new way of issuing commands whenever possible. Sending via a single string remains functional as before, but its implementation is indeed a bit simplistic. I'm not sure yet that I want to work on a fancier string parser, because i think the new way mechanism is a better approach. So.. closed for now.
