### ISSUE TITLE
Command wizard "next" button does not work in v1.0.5

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#83]
In the Command Stack tab, if you click on the Command Wizard button, you then can search the available commands.

After choosing a command, the 'Next' button does not show up the next window where the parameters can be filled.

This works fine in Yamcs Studio 1.0.2.

Reverting commit 73827c20e4e8 did not fix it.
On top of that, reverting commit 9da657d81d fixed it.

So it's safe to say commits 9da657d81d (possibly in combination with 73827c20e4e8) caused the issue to appear.

**Comment by fqqb** [comment]
The fix for this is best done server-side: https://github.com/yamcs/yamcs/compare/a6d4347847dd...d7a310a08fd0
I assume you'll want a 3.4.10 for this?

Basically the Studio did not get the complete model of command arguments and therefore the wizard would throw an exception (you can see that if you run studio from a terminal).

**Comment by tomvanbraeckel** [comment]
A new Yamcs Server 3.4.10 release would be an option, yes. A client-side fix of the regression in Yamcs Studio would alternatively also be an option.

**Comment by fqqb** [comment]
yamcs 3.4.10 was released today with the mentioned server tweak.

I don't plan on reverting or adapting any client code for this issue. The old code was indeed working for your case, but would have failed on other cases where features of a command hierarchy are used more extensively. The current way should be the better approach and matches the master branch more closely.
