### ISSUE TITLE
Telecommand acknowledgement level D flag set to green after level C failure

### ISSUE THREAD

**Issue by alejandiaz** [yamcs/yamcs-studio#86]
A telecommand was issued and failed at level C.  At this point we were expecting the next level D flag to be grey (or even red) but instead it was green. 

Our understating is a green D flag is never expected after a red C flag.

**Comment by fqqb** [comment]
Hi, sorry for late response.
I have the same understanding as you. If you see red, it means there was a negative acknowledgment received by Yamcs.

However this sounds like an issue with the MCS that generates those A, B, C, D command responses, not Yamcs or Yamcs Studio.

So I'm gonna close this issue for that reason, feel free to reopen if you think otherwise.

**Comment by tomvanbraeckel** [comment]
Can we re-open this issue, please?

The "D" flag's behavior is different from the A, B, C flags, so we think it needs special treatment in Yamcs Studio, to behave according to some documentation that was found, and to behave the same as other software, such as "MCS Tools" CDMCS commanding software.

The proposed fix would be: Set the D flag to grey when a previous flag (DASS,MCS,A,B,C) has been set to red.

Rationale: We believe the Yamcs should implement this logic because TC acknowledgement packets are not sent out for the D flag. D flag nominal behavior is to not receive any acknowledgement packet at all, and only receive negative acknowledgement packets when there has been a problem.

Level D means that the stack waits up to three seconds to receive a possible NAK from ISS MDM2; if the NAK is not received within the given time, then successful command execution is assumed. The TransmissionLevel value is 4.
Source: CDMCS User Manual (COL-RIBRE-MA-0086)

At B-USOC we have 3 open tickets (721,1071,1187) where it appears no NAK for flag D was received and C flag was marked as failed. In this case different behaviours were experienced by the client applications:

-    Col-CC client ("MCS Tools") interpreted this setting the D flag to grey.
-    B.USOC Yamcs-Studio client interpreted this setting the D flag to green.

It seems correct to conclude Yamcs-Studio v1.0.6 reacted wrongly to the inputs and should instead behave like the Col-CC client.

We assumed this logic should be implemented on the client side (we use Yamcs Studio 1.0.8) and that MCS Tools also does this. But perhaps in the Yamcs architecture, it would actually make more sense to do this on the server-side. Up to you, we just don't want to see a green dot in the D column :-)

**Comment by fqqb** [comment]
> perhaps in the Yamcs architecture, it would actually make more sense to do this on the server-side

Correct. It's a server issue, specific to our USOC integration plugin(s). Copied this discussion to internal repo for continuation.
