### ISSUE TITLE
Graph enums raw value

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs-studio#91]
If a parameter is definied as enum, one cannot access the raw values / plot it to a graph.
The only workaround is to somehow duplicate the parameter - casting it once as enum - and a second time in its raw value.
Is there a possibilty to integrate it in that way that one could specifiy a value as enum, while still retaining the possibility to graph the raw values?

**Comment by fqqb** [comment]
I think this issue is OK with the fix to #53.

Since v1.5.0 you can use the prefix `raw://` in front of the PV name, this will make that PV connect to raw values as opposed to engineering values of that parameter. So if you use that for an enum with numeric raw, it should give you possibility to plot.

**Comment by nmaas87** [comment]
Thanks Fabian, thats looking very promising!
I forwarded the information and we will need some time to verify the solution, but its looking good so far.
I would keep this issue open and post back any findings
Thank you very much to you and the team 👍🏻

**Comment by fqqb** [comment]
In addition to previous comment, it does appear possible to plot an Enum using the regular (non-raw) parameter reference.
Since Yamcs Studio does not apply any averaging to its realtime plots, this makes more sense than it would in yamcs-web.

Closing as this is old, and addressed a long time back.
