### ISSUE TITLE
Standalone window open mode fails

### ISSUE THREAD

**Issue by mbenson1** [yamcs/yamcs-studio#98]
In the v1.5.3 release of YAMCS Studio, the option to open an OPI as a standalone window works once, but only once.  The first time it opens, you see the following error in the console:

[02:13:16.950] Failed to send OPI shells changed command

When I close the popup window, I see the following additional error:

[02:13:26.950] Failed to send OPI shells changed command

When I click the button again to open the window again, I see the following 2 errors:

[02:21:12.827] Failed to open /MyTest/test2.opi
[02:21:12.828] Failed to open /MyTest/test2.opi

I'm using Ubuntu 16.04

**Comment by fqqb** [comment]
I thought I had remove all standalone references, but you managed to find one still :)

All these different varieties of window tricks were causing big usability problems in the first versions of Yamcs Studio (as they are in CS-Studio), because the Eclipse platform is just not very well suited for that. Same reason why I got rid of most of the top/right/bottom/left options.

My solution here, sorry to say, will be to get rid of some of these action options.

**Comment by fqqb** [comment]
After some more thinking:
* top/left/bottom/right options should be gone for sure (they relate to perspective positions, but that just didn't work well as soon as the user did any sort of layout customization).
* the 'standalone' i will try to fix first. I can see how it could be useful for your scenario.

**Comment by fqqb** [comment]
Issues with standalone windows fixed on master.
